name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup ARM64 arch build
      run: |
        rustup target add aarch64-unknown-linux-gnu && \
        sudo apt install g++-aarch64-linux-gnu && \
        echo -e '[target.aarch64-unknown-linux-gnu]\nlinker = "aarch64-linux-gnu-gcc"' > ~/.cargo/config
    - name: Build
      run: cargo build --target aarch64-unknown-linux-gnu --release
    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.3.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/aarch64-unknown-linux-gnu/release/oci-agent
        asset_name: aarch64-binary
        tag: ${{ github.ref }}
        overwrite: true
        body: "Release ${{ github.ref }}"

